apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config-map
  labels:
    name: kibana-config-map
  namespace: default
data:
  kibana.yml: |-
    server.host: "0.0.0.0"
    server.shutdownTimeout: "5s"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true
    i18n.locale: "zh-CN"
    # elasticsearch.username: kibana_system
    # elasticsearch.password: 12345678